#!/bin/bash

# Steve's script to load a new aram (aramServer) on his simulated robots.
# Heavily cribbed from mobilesoftware/AramServer/putAram.

set -e

# Push aramServer to the EM of a simulated fleet,
# or to all the robots of a real fleet.
ips=(
    10.0.207.231
)

# If we're in a mobilesoftware repo, cd to the top of the repo.
while [ ! -d .git -o ! -d AramServer ]; do
    if [ "$PWD" == / -o -z "$PWD" ]; then
        echo Not in a mobilesoftware repo.
        exit 1
    fi
    cd ..
done

cd AramServer

# Can set to aram, aramCentral, or aramBoth.
# TODO Command line options to pick which.
which=aram

shopt -s nullglob
files=(${which}_*gz)
let n=${#files[*]} || true  # don't fail the script if n is set to 0
if [ 0 -eq $n ]; then
    echo "No files!"
    exit 1
fi

let last=$n-1 || true  # don't fail the script if last is set to 0
latest="${files[$last]}"
unset "files[$last]"
let n=${#files[*]} || true  # don't fail the script if n is set to 0

echo Deploying $latest

# Prevent ssh from doing host key checking, since the host keys of the VMs
# change frequently.
sshNoHost="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

for ip in "${ips[@]}" ; do
    echo to $ip
    sshpass -proot scp $sshNoHost $latest root@$ip:/mnt/rdos
    linkCmd="ln -s /mnt/rdos/$latest /mnt/rdsys/home/admin/"
    sshpass -proot ssh $sshNoHost root@$ip "$linkCmd"
    sleep 1
done

if [ 0 -ne ${#files[*]} ]; then
    echo Deleting old ARAM packages...
    rm -f "${files[@]}"
fi
echo deployAram done.

